### ISSUE TITLE
sku-creator 出现循环render

### ISSUE THREAD

**Issue by Howell5** [tccsg/react-sku#1]
![image](https://user-images.githubusercontent.com/15335257/106770426-ecce8c00-6678-11eb-8eca-f99c00b9e33e.png)

**Comment by Howell5** [comment]
可能是什么问题，如果回复不尽感激

**Comment by tccsg** [comment]
@Howell5 是我这个demo直接运行起来报的错么

**Comment by Howell5** [comment]
@tccsg  不是，copy了 App.tsx 和 components 的内容

**Comment by Howell5** [comment]
如果我要hook到我的项目里，要把 package.json 的 dependency 放进我的项目里吗

**Comment by Howell5** [comment]
或者你发个npm包，我自己装下，这样是不是能解决问题

**Comment by Howell5** [comment]
> @tccsg 不是，copy了 App.tsx 和 components 的内容

哦不是，我直接拿了 components 里的 skuCreator 文件，复制过来，包涵这个文件里用的依赖。然后就只用了这个 skuCreator , 然后把这个组件放到我的组件某个地方里。报错就是这些了

**Comment by tccsg** [comment]
@Howell5  你看下创建一个新的空组件，再把这个skuCreator 引进去看看会不会报警告

**Comment by nuo1693** [comment]
你好，请问有class版本吗

**Comment by tccsg** [comment]
@nuo1693 有的 需要的话 我整理下发出来

**Comment by nuo1693** [comment]
> @nuo1693 有的 需要的话 我整理下发出来

好的，多谢，可以加个qq或者微信吗？

**Comment by tccsg** [comment]
@nuo1693 可以哦 QQ: 547325725
